#!/usr/bin/env python3
"""
Migration script to convert config.py to .env file
This helps secure your configuration by using environment variables instead of committed files.
"""

import os
import sys
from pathlib import Path

def migrate_config_to_env():
    """Migrate config.py to .env file"""
    
    project_root = Path(__file__).parent
    config_py = project_root / "config.py"
    env_file = project_root / ".env"
    env_example = project_root / ".env.example"
    
    # Check if config.py exists
    if not config_py.exists():
        print("❌ config.py not found. Nothing to migrate.")
        return False
    
    # Check if .env already exists
    if env_file.exists():
        response = input("⚠️  .env file already exists. Overwrite? (y/N): ")
        if response.lower() != 'y':
            print("Migration cancelled.")
            return False
    
    # Read config.py
    try:
        # Import config.py safely
        sys.path.insert(0, str(project_root))
        import config as config_module
    except ImportError as e:
        print(f"❌ Error importing config.py: {e}")
        return False
    
    # Read .env.example as template
    env_template = {}
    if env_example.exists():
        with open(env_example, 'r') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key = line.split('=')[0].strip()
                    value = line.split('=', 1)[1].strip()
                    env_template[key] = value
    
    # Map config.py values to .env
    env_content = []
    env_content.append("# FalconEye Environment Configuration")
    env_content.append("# Generated by migrate_to_env.py")
    env_content.append("# NEVER commit this file to version control!")
    env_content.append("")
    
    # Application settings
    env_content.append("# ============================================")
    env_content.append("# Application Settings")
    env_content.append("# ============================================")
    env_content.append(f"FLASK_ENV=development")
    env_content.append(f"FLASK_PORT={getattr(config_module, 'FLASK_PORT', 3001)}")
    env_content.append(f"FALCONEYE_SECRET=your-secret-key-here-change-in-production")
    env_content.append("")
    
    # Camera configuration
    env_content.append("# ============================================")
    env_content.append("# Camera Configuration")
    env_content.append("# ============================================")
    camera_ip = getattr(config_module, 'CAMERA_IP', '')
    if camera_ip:
        env_content.append(f"CAM1_URL=http://{camera_ip}/jpg")
    else:
        env_content.append("CAM1_URL=http://10.103.190.6/jpg")
    env_content.append("CAM2_URL=")
    env_content.append("ESP_PAN_BASE_URL=")
    env_content.append("")
    
    # AWS S3 Configuration
    env_content.append("# ============================================")
    env_content.append("# AWS S3 Configuration (Optional)")
    env_content.append("# ============================================")
    aws_key = getattr(config_module, 'AWS_ACCESS_KEY_ID', '')
    aws_secret = getattr(config_module, 'AWS_SECRET_ACCESS_KEY', '')
    aws_region = getattr(config_module, 'AWS_REGION', 'us-east-1')
    aws_bucket = getattr(config_module, 'AWS_BUCKET', 'falconeye-clips')
    
    if aws_key and aws_key != "your_access_key_here":
        env_content.append(f"AWS_ACCESS_KEY_ID={aws_key}")
    else:
        env_content.append("AWS_ACCESS_KEY_ID=your_access_key_here")
    
    if aws_secret and aws_secret != "your_secret_key_here":
        env_content.append(f"AWS_SECRET_ACCESS_KEY={aws_secret}")
    else:
        env_content.append("AWS_SECRET_ACCESS_KEY=your_secret_key_here")
    
    env_content.append(f"AWS_REGION={aws_region}")
    env_content.append(f"S3_BUCKET_NAME={aws_bucket}")
    env_content.append("")
    
    # Firebase Configuration
    env_content.append("# ============================================")
    env_content.append("# Firebase Cloud Messaging (Optional)")
    env_content.append("# ============================================")
    fcm_key = getattr(config_module, 'FCM_SERVER_KEY', '')
    if fcm_key and fcm_key != "your_firebase_server_key_here":
        env_content.append(f"FCM_SERVER_KEY={fcm_key}")
    else:
        env_content.append("FCM_SERVER_KEY=your_firebase_server_key_here")
    env_content.append("FIREBASE_PROJECT_ID=your_project_id_here")
    env_content.append("")
    
    # AI Model Configuration
    env_content.append("# ============================================")
    env_content.append("# AI Model Configuration")
    env_content.append("# ============================================")
    env_content.append("DEVICE=auto")
    env_content.append("DETECT_MODEL_NAME=yolov8s.pt")
    env_content.append("LIVE_MODEL_NAME=yolov8n.pt")
    env_content.append("")
    
    # Feature Flags
    env_content.append("# ============================================")
    env_content.append("# Feature Flags")
    env_content.append("# ============================================")
    env_content.append("FALCONEYE_FACES_ENABLED=true")
    env_content.append("FALCONEYE_DISABLE_FACE_RECOGNITION=false")
    env_content.append("TEST_MODE=false")
    
    # Write .env file
    try:
        with open(env_file, 'w') as f:
            f.write('\n'.join(env_content))
        print(f"✅ Created .env file at {env_file}")
    except Exception as e:
        print(f"❌ Error writing .env file: {e}")
        return False
    
    # Ask about removing config.py
    print("\n⚠️  SECURITY WARNING:")
    print("   Your config.py file may contain sensitive credentials.")
    print("   Consider removing it after verifying .env works correctly.")
    response = input("\nRemove config.py now? (y/N): ")
    if response.lower() == 'y':
        try:
            # Backup first
            backup = project_root / "config.py.backup"
            if not backup.exists():
                import shutil
                shutil.copy(config_py, backup)
                print(f"✅ Backed up config.py to {backup}")
            
            config_py.unlink()
            print("✅ Removed config.py")
        except Exception as e:
            print(f"⚠️  Could not remove config.py: {e}")
            print("   Please remove it manually after verifying .env works.")
    
    print("\n✅ Migration complete!")
    print("\nNext steps:")
    print("1. Review and update .env with any missing values")
    print("2. Test the application: python backend.py")
    print("3. Add .env to .gitignore (already done)")
    print("4. Remove config.py from git history if it was committed:")
    print("   git rm --cached config.py")
    print("   git commit -m 'Remove config.py from version control'")
    
    return True

if __name__ == "__main__":
    migrate_config_to_env()

